# Generated by Django 3.1.7 on 2022-03-16 07:30

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('Pakistan', 'Pakistan'), ('England', 'England'), ('India', 'India'), ('America', 'America')], max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='gallery-images/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='review-images/')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('quote', models.CharField(max_length=500, verbose_name='Quote')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(blank=True, upload_to='images/')),
                ('duration', models.IntegerField()),
                ('tour_type', models.IntegerField()),
                ('group', models.IntegerField()),
                ('languages', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=700, verbose_name='OverView')),
                ('departure_time', models.DateField()),
                ('return_time', models.DateField()),
                ('included', multiselectfield.db.fields.MultiSelectField(choices=[('Private Transport', 'Private Transport'), ('Entrance Fees', 'Entrance Fees'), ('Box Lunch', 'Box Lunch'), ('Additional Services', ' Additional Services'), ('Insurance', 'Insurance'), ('Drink', 'Drink'), ('Tickets', 'Tickets')], max_length=200)),
                ('excluded', multiselectfield.db.fields.MultiSelectField(choices=[('Private Transport', 'Private Transport'), ('Entrance Fees', 'Entrance Fees'), ('Box Lunch', 'Box Lunch'), ('Additional Services', ' Additional Services'), ('Insurance', 'Insurance'), ('Drink', 'Drink'), ('Tickets', 'Tickets')], max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.location')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.location')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.city')),
            ],
            options={
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('image', models.FileField(blank=True, upload_to='guide-images/')),
                ('fb', models.CharField(blank=True, max_length=400, verbose_name='Facebook Link')),
                ('insta', models.CharField(blank=True, max_length=400, verbose_name='Instagram Link')),
                ('twiter', models.CharField(blank=True, max_length=400, verbose_name='Twiter Link')),
                ('whatsapp', models.CharField(blank=True, max_length=400, verbose_name='Whatsapp Number')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('duration', models.IntegerField()),
                ('tour_type', models.IntegerField()),
                ('group', models.IntegerField()),
                ('languages', models.CharField(max_length=200)),
                ('overview', models.CharField(max_length=700, verbose_name='OverView')),
                ('departure_time', models.DateField()),
                ('return_time', models.DateField()),
                ('included', multiselectfield.db.fields.MultiSelectField(choices=[('Private Transport', 'Private Transport'), ('Entrance Fees', 'Entrance Fees'), ('Box Lunch', 'Box Lunch'), ('Additional Services', ' Additional Services'), ('Insurance', 'Insurance'), ('Drink', 'Drink'), ('Tickets', 'Tickets')], max_length=200)),
                ('excluded', multiselectfield.db.fields.MultiSelectField(choices=[('Private Transport', 'Private Transport'), ('Entrance Fees', 'Entrance Fees'), ('Box Lunch', 'Box Lunch'), ('Additional Services', ' Additional Services'), ('Insurance', 'Insurance'), ('Drink', 'Drink'), ('Tickets', 'Tickets')], max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.location')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.city')),
            ],
        ),
    ]
